repos:
-   repo: https://github.com/pre-commit/mirrors-yapf
    rev: v0.30.0
    hooks:
    -   id: yapf
        args: [--in-place, --parallel, --recursive, --style, .yapf-config]
        files: "^(compliance|test)"
        stages: [commit]
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
    -   id: flake8
        args: [
          --extend-ignore,
          "P1,C812,C813,C814,C815,C816,W503"
        ]
        additional_dependencies: [
          flake8-2020,
          flake8-broken-line,
          flake8-bugbear,
          flake8-builtins,
          flake8-commas,
          flake8-comprehensions,
          flake8-docstrings,
          flake8-eradicate,
          flake8-import-order,
          flake8-mutable,
          flake8-pep3101,
          flake8-print,
          flake8-quotes,
          flake8-string-format,
          flake8-use-fstring,
          pep8-naming
        ]
        files: "^(compliance|test)"
        stages: [commit]
