repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      -   id: trailing-whitespace
      -   id: check-yaml
      -   id: fix-encoding-pragma
          args: ["--remove"]  # Not needed on python3
-   repo: https://github.com/ambv/black
    rev: 24.4.2
    hooks:
      - id: black
-   repo: https://github.com/PyCQA/flake8
    rev: 7.1.0
    hooks:
    -   id: flake8
        files: "^(compliance|test|demo)"
-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.9
    hooks:
    -   id: bandit
        args: [--recursive]
        files: "^(compliance|test)"
